# Site settings
title: 크리에이티브 커먼즈 라이선스
description: >
  크리에이티브커먼즈 라이선스(Creative Commons License)는 창작자가 자신의 창작물에 대하여 일정한 조건하에 모든 이의 자유이용을 허락하는 라이선스 입니다.
baseurl: '/' # the subpath of your site, e.g. /blog/
url: 'http://ccl.cckorea.org' # the base hostname & protocol for your site
permalink: pretty
timezone: Asia/Seoul

email: creative@cckorea.org
twitter_username: cckorea
github_username: creativecommonskorea

locale: ko
# locale_alt:

# 공유용 대표 이미지 (트위터 페북 카드 이미지)
default_image: '/images/share/ccl_sns_img_green.jpg'

# 초기 화면
numbers_of_showcases_to_display: 4

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed
  sourcemap: true

exclude: [ Gemfile, Gemfile.lock, README.md, front/uploads.md ]

# Collection
collections:
  showcases:
    output: true
    permalink: /showcase/:path/
  resources:
    output: true
    permalink: /resource/:path/

defaults:
  -
    scope:
      path: "showcases"
    values:
      layout: "showcase"
    scope:
      path: "resources"
    values:
      layout: "resource"

# Prose.io settings
prose:
  rooturl: ''
  siteurl: 'http://ccl.cckorea.org'
  relativeLinks: 'http://ccl.cckorea.org/links.jsonp'
  media: 'media'
  metadata:
    pages:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'page'
      - name: 'title'
        field:
          element: 'text'
          label: '제목'
          value: ''
      - name: 'permalink'
        field:
          element: 'text'
          label: '퍼머링크'
          help: 'URL. 예시) /about/cclicense/'
          value: ''
      - name: 'description'
        field:
          element: 'textarea'
          label: '요약 설명'
          help: '검색 엔진에게 제공할 설명, 초기 화면에 표시할 요약입니다.'
          value: ''
      - name: 'quiz_show'
        field:
          element: 'checkbox'
          label: '하단에 OX 퀴즈 표시하'
          value: 'false'
      - name: 'quiz_o_title'
        field:
          element: 'textarea'
          label: 'O 퀴즈 제목'
          help: '줄바꿈을 존중합니다.'
      - name: 'quiz_o_desc'
        field:
          element: 'textarea'
          label: 'O 퀴즈 본문'
          help: '줄바꿈을 존중합니다.'
      - name: 'quiz_x_title'
        field:
          element: 'textarea'
          label: 'X 퀴즈 제목'
          help: '줄바꿈을 존중합니다.'
      - name: 'quiz_x_desc'
        field:
          element: 'textarea'
          label: 'X 퀴즈 본문'
          help: '줄바꿈을 존중합니다.'
      - name: 'related_contents'
        field:
          element: 'textarea'
          label: 'X 퀴즈 본문'
    _showcases:
    _faq:
